In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC

In [2]:
df = pd.read_csv('teraPromiseRevised.csv', encoding = "ISO-8859-1")

In [3]:
df.head()

projectid                                        requirement  category
0          1  'The system shall refresh the display every 60...         0
1          1  'The application shall match the color of the ...         0
2          1  ' If projected  the data must be readable.  On...         0
3          1  ' The product shall be available during normal...         0
4          1  ' If projected  the data must be understandabl...         0

In [4]:
X = df['requirement']
y = df['category']

In [5]:
#Cleaning up the data

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
# model, secs = build(classifier, X_train, y_train)

In [8]:
#CountVectorizer allows us to convert text to vecors using the bag-of-words approach
#Instatiate the CountVectorizer

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [10]:
#instantiate CountVectorizer (vectorizer)
vect = TfidfVectorizer(min_df=1, stop_words='english', decode_error='ignore')

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)

In [12]:
# fit
# learn the 'vocabulary' of the training data (occurs in-place)
X_trainvect= vect.fit_transform(X_train)

In [13]:
X_trainvect.shape

(500, 1320)

In [14]:
a=X_trainvect.toarray()

In [15]:
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [16]:
a[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [17]:
vect.inverse_transform(a[0])

[array([u'affected', u'affecting', u'cancellations', u'capacity',
        u'changes', u'clinical', u'clinicals', u'including', u'limited',
        u'notify', u'occur', u'parties', u'section'], dtype='<U16')]

In [18]:
len(a[0])

1320

In [19]:
# examine the fitted vocabulary
vect.get_feature_names()

[u'000',
 u'00am',
 u'00amd',
 u'10',
 u'100',
 u'1000',
 u'10x10',
 u'11',
 u'15',
 u'150',
 u'1500',
 u'20',
 u'2000',
 u'24',
 u'24x7',
 u'24x7x365',
 u'25',
 u'256k',
 u'30',
 u'30min',
 u'350',
 u'365',
 u'3am',
 u'400mb',
 u'50',
 u'56k',
 u'59pm',
 u'5pm',
 u'60',
 u'6pm',
 u'70',
 u'700',
 u'7am',
 u'7pm',
 u'80',
 u'800',
 u'800x600',
 u'8am',
 u'8pm',
 u'90',
 u'95',
 u'97',
 u'98',
 u'99',
 u'999',
 u'9am',
 u'ability',
 u'able',
 u'abuse',
 u'academic',
 u'acceptable',
 u'access',
 u'accessed',
 u'accesses',
 u'accessible',
 u'accessing',
 u'accommodate',
 u'accomplish',
 u'accordance',
 u'according',
 u'accordingly',
 u'account',
 u'accounting',
 u'accounts',
 u'accurately',
 u'achieve',
 u'acknowledgements',
 u'act',
 u'action',
 u'actions',
 u'activate',
 u'activated',
 u'active',
 u'activities',
 u'activity',
 u'actor',
 u'actual',
 u'ad',
 u'add',
 u'added',
 u'addition',
 u'additions',
 u'address',
 u'addresses',
 u'adequately',
 u'adhere',
 u'adjacent',
 u'adjust',
 

In [20]:
svm = SVC(kernel='linear')

In [21]:
y_train = y_train.astype('int')

In [22]:
svm.fit(X_trainvect, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [23]:
X_testvect= vect.transform(X_test) 

In [24]:
#pred = mnb.predict(X_trainvect)

In [25]:
#pred

In [26]:
b = X_testvect.toarray()

In [27]:
b

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
X_trainvect.shape

(500, 1320)

In [29]:
y_train.shape

(500L,)

In [30]:
X_testvect

<125x1320 sparse matrix of type '<type 'numpy.float64'>'
	with 1056 stored elements in Compressed Sparse Row format>

In [31]:
X_testvect.shape

(125, 1320)

In [32]:
y_test = y_test.astype('int')

In [33]:
pred = svm.predict(X_testvect)

In [34]:
# calculate accuracy of class predictions
from sklearn import metrics
from sklearn.metrics import f1_score

In [35]:
metrics.accuracy_score(y_test, pred)

0.92

In [36]:
# f1 score
score = f1_score(y_test, pred)

# print
print("F1 score: {:.2f}".format(score))

F1 score: 0.44


In [37]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
from pandas.tools.plotting import scatter_matrix
%matplotlib inline

C:\Users\Prue\Anaconda2\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using Theano backend.


## Create a Deep Neural Network Classifier with 5 layers and 1000 neurons per layer
use a dropout to prevent overfitting 

In [38]:
model = Sequential()
model.add(Dense(1000, input_dim=X_trainvect.shape[1], kernel_initializer='uniform', activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1000, kernel_initializer='uniform', activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1000, kernel_initializer='uniform', activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1000, kernel_initializer='uniform', activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))

## Print Model Summary

In [39]:
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1000)              1321000   
_________________________________________________________________
dropout_1 (Dropout)          (None, 1000)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 1000)              1001000   
_________________________________________________________________
dropout_2 (Dropout)          (None, 1000)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 1000)              1001000   
_________________________________________________________________
dropout_3 (Dropout)          (None, 1000)              0         
_________________________________________________________________
dense_4 (Dense)              (None, 1000)              1001000   
__________

## Compile the model

In [40]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

## Fit the model

In [41]:
model.fit(X_trainvect, y_train, epochs=500, batch_size=25, verbose=1)

Epoch 1/500
500/500 [==============================] - 2s 3ms/step - loss: 0.4027 - acc: 0.8600
Epoch 2/500
500/500 [==============================] - 1s 2ms/step - loss: 0.1785 - acc: 0.8960
Epoch 3/500
500/500 [==============================] - 1s 2ms/step - loss: 0.0784 - acc: 0.9320
Epoch 4/500
500/500 [==============================] - 1s 2ms/step - loss: 0.0619 - acc: 1.0000
Epoch 5/500
500/500 [==============================] - 1s 2ms/step - loss: 0.0190 - acc: 0.9980
Epoch 6/500
500/500 [==============================] - 1s 2ms/step - loss: 0.0022 - acc: 1.0000
Epoch 7/500
500/500 [==============================] - 1s 2ms/step - loss: 0.0021 - acc: 1.0000
Epoch 8/500
500/500 [==============================] - 1s 2ms/step - loss: 0.0166 - acc: 0.9980
Epoch 9/500
500/500 [==============================] - 1s 2ms/step - loss: 0.0037 - acc: 0.9980
Epoch 10/500
500/500 [==============================] - 1s 2ms/step - loss: 2.6170e-04 - acc: 1.0000
Epoch 11/500
500/500 [=============

500/500 [==============================] - 5s 9ms/step - loss: 1.0659e-07 - acc: 1.0000
Epoch 161/500
500/500 [==============================] - 5s 9ms/step - loss: 1.9561e-07 - acc: 1.0000
Epoch 162/500
500/500 [==============================] - 5s 9ms/step - loss: 1.2014e-07 - acc: 1.0000
Epoch 163/500
500/500 [==============================] - 4s 9ms/step - loss: 1.5757e-07 - acc: 1.0000
Epoch 164/500
500/500 [==============================] - 4s 9ms/step - loss: 1.0557e-07 - acc: 1.0000
Epoch 165/500
500/500 [==============================] - 4s 9ms/step - loss: 5.8003e-07 - acc: 1.0000
Epoch 166/500
500/500 [==============================] - 4s 9ms/step - loss: 1.0460e-07 - acc: 1.0000
Epoch 167/500
500/500 [==============================] - 5s 9ms/step - loss: 1.8943e-07 - acc: 1.0000
Epoch 168/500
500/500 [==============================] - 5s 9ms/step - loss: 3.2844e-07 - acc: 1.0000
Epoch 169/500
500/500 [==============================] - 5s 9ms/step - loss: 1.3454e-07 - acc: 1

500/500 [==============================] - 5s 9ms/step - loss: 1.0560e-07 - acc: 1.0000
Epoch 321/500
500/500 [==============================] - 5s 9ms/step - loss: 1.1231e-07 - acc: 1.0000
Epoch 322/500
500/500 [==============================] - 5s 9ms/step - loss: 1.0200e-07 - acc: 1.0000
Epoch 323/500
500/500 [==============================] - 5s 9ms/step - loss: 1.0627e-07 - acc: 1.0000
Epoch 324/500
500/500 [==============================] - 5s 9ms/step - loss: 1.0247e-07 - acc: 1.0000
Epoch 325/500
500/500 [==============================] - 5s 9ms/step - loss: 1.0286e-07 - acc: 1.0000
Epoch 326/500
500/500 [==============================] - 5s 9ms/step - loss: 1.0267e-07 - acc: 1.0000
Epoch 327/500
500/500 [==============================] - 5s 9ms/step - loss: 1.0247e-07 - acc: 1.0000
Epoch 328/500
500/500 [==============================] - 5s 9ms/step - loss: 1.0331e-07 - acc: 1.0000
Epoch 329/500
500/500 [==============================] - 5s 10ms/step - loss: 1.1199e-07 - acc: 

500/500 [==============================] - 6s 11ms/step - loss: 1.0200e-07 - acc: 1.0000
Epoch 479/500
500/500 [==============================] - 6s 11ms/step - loss: 1.0200e-07 - acc: 1.0000
Epoch 480/500
500/500 [==============================] - 6s 11ms/step - loss: 1.0343e-07 - acc: 1.0000
Epoch 481/500
500/500 [==============================] - 6s 11ms/step - loss: 1.0200e-07 - acc: 1.0000
Epoch 482/500
500/500 [==============================] - 6s 11ms/step - loss: 1.0200e-07 - acc: 1.0000
Epoch 483/500
500/500 [==============================] - 5s 11ms/step - loss: 1.0200e-07 - acc: 1.0000
Epoch 484/500
500/500 [==============================] - 5s 11ms/step - loss: 1.6676e-07 - acc: 1.0000
Epoch 485/500
500/500 [==============================] - 5s 11ms/step - loss: 1.0206e-07 - acc: 1.0000
Epoch 486/500
500/500 [==============================] - 5s 11ms/step - loss: 1.0200e-07 - acc: 1.0000
Epoch 487/500
500/500 [==============================] - 5s 11ms/step - loss: 2.0171e-0

## Evaluate the model accuracy

In [46]:
scores = model.evaluate(X_testvect, y_test, verbose=1)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

125/125 [==============================] - 0s 81us/step
acc: 94.40%


The Deep Neural Network has out peformed the SVM

## Calculate the F1 Score

In [47]:
dnn_pred = model.predict_classes(X_testvect)

In [48]:
# f1 score
score_f1 = f1_score(y_test, dnn_pred)

# print
print("F1 score: {:.2f}".format(score_f1))

F1 score: 0.67
